<?php
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$_product = $block->getProduct();

$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('Magento\Store\Model\StoreManagerInterface')->getStore();
$mediaUrl = $storeManager->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);
$currentStoreId = $storeManager->getStoreId();

function classification($cType, $optionId, $currentStoreId){
    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $res = $objectManager->get('Magento\Framework\App\ResourceConnection');
    $connection = $res->getConnection();
    $tableName = $res->getTableName('zenon_classification');
    if($cType == 'bc'):
        $select = 'SELECT * FROM `'.$tableName.'` WHERE bc_option_id='.$optionId.' AND store_id='.$currentStoreId;
        $classification = $connection->fetchAll($select);
        if(count($classification) == 0):
            $select = 'SELECT * FROM `'.$tableName.'` WHERE bc_option_id='.$optionId.' AND store_id=0';
            $classification = $connection->fetchAll($select);
        endif;
    elseif ($cType == 'fec'):
        $select = 'SELECT * FROM `'.$tableName.'` WHERE fec_option_id='.$optionId.' AND store_id='.$currentStoreId;
        $classification = $connection->fetchAll($select);
        if(count($classification) == 0):
            $select = 'SELECT * FROM `'.$tableName.'` WHERE fec_option_id='.$optionId.' AND store_id=0';
            $classification = $connection->fetchAll($select);
        endif;
    elseif ($cType == 'feca1'):
        $select = 'SELECT * FROM `'.$tableName.'` WHERE fec1_option_id='.$optionId.' AND store_id='.$currentStoreId;
        $classification = $connection->fetchAll($select);
        if(count($classification) == 0):
            $select = 'SELECT * FROM `'.$tableName.'` WHERE fec1_option_id='.$optionId.' AND store_id=0';
            $classification = $connection->fetchAll($select);
        endif;
    elseif ($cType == 'feca2'):
        $select = 'SELECT * FROM `'.$tableName.'` WHERE fec2_option_id='.$optionId.' AND store_id='.$currentStoreId;
        $classification = $connection->fetchAll($select);
        if(count($classification) == 0):
            $select = 'SELECT * FROM `'.$tableName.'` WHERE fec2_option_id='.$optionId.' AND store_id=0';
            $classification = $connection->fetchAll($select);
        endif;
    elseif ($cType == 'et'):
        $select = 'SELECT * FROM `'.$tableName.'` WHERE et_option_id='.$optionId.' AND store_id='.$currentStoreId;
        $classification = $connection->fetchAll($select);
        if(count($classification) == 0):
            $select = 'SELECT * FROM `'.$tableName.'` WHERE et_option_id='.$optionId.' AND store_id=0';
            $classification = $connection->fetchAll($select);
        endif;
    else:
        $select = 'SELECT * FROM `'.$tableName.'` WHERE fc_option_id='.$optionId.' AND store_id='.$currentStoreId;
        $classification = $connection->fetchAll($select);
        if(count($classification) == 0):
            $select = 'SELECT * FROM `'.$tableName.'` WHERE fc_option_id='.$optionId.' AND store_id=0';
            $classification = $connection->fetchAll($select);
        endif;
    endif;

    return $classification;
}
function classificationPrint($classifications, $mediaUrl){
    $classification = end($classifications);
    $imagePath = $classification['image'];
    $description = $classification['description'];
    $info = $classification['info'];
    $status = $classification['status'];
    $imageUrl = $mediaUrl.$imagePath;
    $id = uniqid('zd-popup');
    if($status == 1):
        $html = '<li class="clearfix">'.
            '<img class="zd-tooltip" src="' . $imageUrl . '">'.
            '<div class="zd-feature">' .
                strip_tags($description) .
                '<a href="#" class="zdPopInfo" data-modal-id="' . $id . '"></a>' .
            '</div>' .
            '<div id="' . $id . '" class="zd-modal-box" style="display: none;">' .
                '<a href="#" class="zd-modal-close"></a>' .
                '<div class="zd-modal-box-inner std clearfix">' .
                    $info .
                '</div>' .
            '</div>' .
        '</li>';
    else:
        $html = '';
    endif;

    return $html;
}
?>

<?php if($_product->getBurglaryClassification() != '' || $_product->getFireExtinguisherCert() != '' || $_product->getFireExtinguisherCertAdd1() != '' || $_product->getFireExtinguisherCertAdd2() != '' || $_product->getEasTechnology() != '' || $_product->getFireClassification() != ''):?>
    <div class="zd-cat-description-right">
        <ul class="clearfix">
            <?php
            $burglaryClassification = $_product->getBurglaryClassification();
            if($burglaryClassification != '' && $burglaryClassification != '0'){
                $bcs = classification('bc', $burglaryClassification, $currentStoreId);
                if(count($bcs) != 0):
                    echo classificationPrint($bcs, $mediaUrl);
                endif;
            }
            $fireExtinguisherCert = $_product->getFireExtinguisherCert();
            if($fireExtinguisherCert != '' && $fireExtinguisherCert != '0'){
                $fecs = classification('fec', $fireExtinguisherCert, $currentStoreId);
                if(count($fecs) != 0):
                    echo classificationPrint($fecs, $mediaUrl);
                endif;
            }
            $fireExtinguisherCertAdd1 = $_product->getFireExtinguisherCertAdd1();
            if($fireExtinguisherCertAdd1 != '' && $fireExtinguisherCertAdd1 != '0'){
                $feca1s = classification('feca1', $fireExtinguisherCertAdd1, $currentStoreId);
                if(count($feca1s) != 0):
                    echo classificationPrint($feca1s, $mediaUrl);
                endif;
            }
            $fireExtinguisherCertAdd2 = $_product->getFireExtinguisherCertAdd2();
            if($fireExtinguisherCertAdd2 != '' && $fireExtinguisherCertAdd2 != '0'){
                $feca2s = classification('feca2', $fireExtinguisherCertAdd2, $currentStoreId);
                if(count($feca2s) != 0):
                    echo classificationPrint($feca2s, $mediaUrl);
                endif;
            }
            $easTechnology = $_product->getEasTechnology();
            if($easTechnology != '' && $easTechnology != '0'){
                $ets = classification('et', $easTechnology, $currentStoreId);
                if(count($ets) != 0):
                    echo classificationPrint($ets, $mediaUrl);
                endif;
            }
            $fireClassification = $_product->getFireClassification();
            if($fireClassification != '' && $fireClassification != '0'){
                $fcs = classification('fc', $fireClassification, $currentStoreId);
                if($fcs != 0):
                    echo classificationPrint($fcs, $mediaUrl);
                endif;
            }
            ?>
        </ul>
    </div>

    <script type="text/javascript">
        require(['jquery','zColorBox','zTooltipster'],function () {
            jQuery(document).ready(function () {
                jQuery('#popup').on('click', function(){
                    jQuery('body').addClass('popup-active');
                });
                jQuery('#close').on('click', function(){
                    jQuery('body').removeClass('popup-active');
                });

                jQuery('.zd-tooltip').tooltipster({
                    maxWidth: 160,
                    contentAsHTML: true
                });

                jQuery('.zd-tooltip').tooltipster({
                    maxWidth: 160,
                    contentAsHTML: true
                });

                jQuery( ".delivery-tooltip" ).hover(function() {
                    jQuery( ".delivery-conditions-tooltip" ).toggleClass("showMeTheTooltip");
                });

                jQuery( ".price-tooltip" ).hover(function() {
                    jQuery( ".price-conditions-tooltip" ).toggleClass("showMeTheTooltip");
                });

                jQuery(".zd-cat-description-right ul li img").click(function() {
                    jQuery(this).closest("li").find(".zdPopInfo").click();
                });

                //pop up
                var appendthis =  ("<div class='zd-modal-overlay'></div>");

                jQuery('a[data-modal-id]').click(function(e) {
                    e.preventDefault();
                    jQuery("body").append(appendthis);
                    jQuery(".zd-modal-overlay").fadeTo(500, 0.7);
                    var modalBox = jQuery(this).attr('data-modal-id');
                    jQuery('#'+modalBox).fadeIn(jQuery(this).data());
                });

                jQuery(document).on("click",".zd-modal-close, .zd-modal-overlay", function(e) {
                    e.preventDefault();
                    jQuery(".zd-modal-box, .zd-modal-overlay").fadeOut(500, function() {
                        jQuery(".zd-modal-overlay").remove();
                    });
                });

                jQuery(window).resize(function() {
                    jQuery(".zd-modal-box").css({
                        top: (jQuery(window).height() - jQuery(".zd-modal-box").outerHeight()) / 2,
                        left: (jQuery(window).width() - jQuery(".zd-modal-box").outerWidth()) / 2
                    });
                });
                jQuery(window).resize();
            });
        });
    </script>
<?php endif;?>