<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Store switcher template
 *
 * @see \Magento\Store\Block\Store\Switcher
 */
?>
<?php if (count($block->getGroups())>1): ?>
<div class="switcher store switcher-store" id="switcher-store">
    <label for="select-store"><?php echo __('Select Store') ?></label>
    <select id="select-store" title="<?php echo __('Your Store') ?>" onchange="window.location.href=this.value" class="flags">
    <?php foreach ($block->getGroups() as $_group): ?>
        <?php $_selected = ($_group->getId() == $block->getCurrentGroupId()) ? ' selected="selected"' : '' ?>
        <option value="<?php echo $_group->getDefaultStore()->getCurrentUrl() ?>" <?php echo $_selected ?>><?php echo $block->escapeHtml($_group->getName()) ?></option>
    <?php endforeach; ?>
    </select>
</div>
<?php endif; ?>
<?php
$_helper = $this->helper('Smartwave\Porto\Helper\Data');

$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$_websites = $storeManager->getWebsites();
$_websiteData = array();
foreach($_websites as $website){
    foreach($website->getStores() as $store){
        $wedsiteId = $website->getId();
        $wedsiteCode = $website->getCode();
        $defaltStoreName = $website->getDefaultStore()->getName();
        $defaltStoreCurrUrl = $website->getDefaultStore()->getCurrentUrl();
        $storeObj = $storeManager->getStore($store);
        $name = $website->getName();
        $url = $storeObj->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_WEB);
        array_push($_websiteData, array('name' => $name,'url' => $url,'id' => $wedsiteId,'code' => $wedsiteCode,'store_name' => $defaltStoreName, 'current_url' => $defaltStoreCurrUrl));
    }
}
$websites = $_websiteData;
$currWebsiteid = $storeManager->getStore()->getWebsiteId();
$currStorename = $storeManager->getStore()->getName();
?>
<?php if (count($websites)>1): ?>
    <div class="switcher store switcher-store" id="switcher-store">
        <label for="select-store"><?php echo __('Select Store') ?></label>
        <select id="select-store" title="<?php echo __('Your Store') ?>" onchange="window.location.href=this.value" class="flags">
            <?php foreach ($websites as $website): ?>
                <?php $_selected = ($website['id'] == $currWebsiteid) ? ' selected="selected"' : '' ?>
                <option value="<?php echo $website['url'] ?>" <?php echo $_selected ?>><?php echo $block->escapeHtml($website['store_name']) ?></option>
            <?php endforeach; ?>
        </select>
    </div>
<?php endif; ?>
