<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>

<?php
/** @var \Magento\Catalog\Pricing\Render\FinalPriceBox $block */

$productId = $block->getSaleableItem()->getId();

/** @var \Magento\Catalog\Pricing\Price\RegularPrice $priceModel */
$priceModel = $block->getPriceType('regular_price');

/** @var \Magento\Catalog\Pricing\Price\FinalPrice $finalPriceModel */
$finalPriceModel = $block->getPriceType('final_price');
$idSuffix = $block->getIdSuffix() ? $block->getIdSuffix() : '';
$schema = ($block->getZone() == 'item_view') ? true : false;
?>

<?php $objectManager = \Magento\Framework\App\ObjectManager::getInstance();?>
<?php $_product = $objectManager->get('Magento\Catalog\Model\Product')->load($productId);?>
<?php $zenon_helper = $this->helper('Zenon\Themesetting\Helper\Data');?>
<?php $zcfp_enable = $zenon_helper->getConfig('zenon_call_for_price/general/zcfp_enable');?>
<?php $zcfp_text = $zenon_helper->getConfig('zenon_call_for_price/general/zcfp_text');?>
<?php $zcfp_mobile = $zenon_helper->getConfig('zenon_call_for_price/general/zcfp_mobile');?>
<?php $product_cfp = $_product->getCallForPrice();?>

<?php if($zcfp_enable == 1 && $product_cfp == 1):?>
    <div class="price-box callforprice without-qty">
        <span class="price-container">
            <span class="price-wrapper">
                <?php $id = uniqid('zd-popup');?>
                <span class="price call_for_price zdPopInfo" data-modal-id="<?php echo $id;?>"><?php echo $zcfp_text;?></span>
                <div id="<?php echo $id;?>" class="zd-modal-box" style="display: none;">
                    <span href="#" class="zd-modal-close"></span>
                    <div class="zd-modal-box-inner std clearfix">
                        <h4 style="margin: 0;"><?php echo $zcfp_mobile;?></h4>
                    </div>
                </div>
            </span>
        </span>
    </div>
<?php else:?>
    <?php if ($block->hasSpecialPrice()): ?>
        <span class="old-price">
            <?php echo $block->renderAmount($priceModel->getAmount(), [
                'display_label'     => __('Regular Price'),
                'price_id'          => $block->getPriceId('old-price-' . $idSuffix),
                'price_type'        => 'oldPrice',
                'include_container' => true,
                'skip_adjustments'  => true
            ]); ?>
        </span>
        <span class="special-price">
            <?php echo $block->renderAmount($finalPriceModel->getAmount(), [
                'display_label'     => __('Special Price'),
                'price_id'          => $block->getPriceId('product-price-' . $idSuffix),
                'price_type'        => 'finalPrice',
                'include_container' => true,
                'schema' => $schema
            ]); ?>
        </span>
    <?php else: ?>
        <?php echo $block->renderAmount($finalPriceModel->getAmount(), [
            'price_id'          => $block->getPriceId('product-price-' . $idSuffix),
            'price_type'        => 'finalPrice',
            'include_container' => true,
            'schema' => $schema
        ]); ?>
    <?php endif; ?>

    <?php if ($block->showMinimalPrice()): ?>
        <?php if ($block->getUseLinkForAsLowAs()):?>
            <a href="<?php echo $block->getSaleableItem()->getProductUrl(); ?>" class="minimal-price-link">
                <?php echo $block->renderAmountMinimal(); ?>
            </a>
        <?php else:?>
            <span class="minimal-price-link">
                <?php echo $block->renderAmountMinimal(); ?>
            </span>
        <?php endif?>
    <?php endif; ?>
<?php endif; ?>