<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * Category left navigation
 *
 * @var $block \Magento\Catalog\Block\Navigation
 */
?>
<?php /*if (!$block->getCategory()) {
    return;
} ?>
<?php $_categories = $block->getCurrentChildCategories(); ?>
<?php $_count = is_array($_categories) ? count($_categories) : $_categories->count(); ?>
<?php if ($_count): ?>
    <div class="block filter">
        <div class="title">
            <strong><?php echo __('Shop By') ?></strong>
        </div>
        <div class="content">
            <strong class="subtitle"><?php echo __('Shopping Options') ?></strong>
            <dl class="options" id="narrow-by-list2">
                <dt><?php echo __('Category') ?></dt>
                <dd>
                    <ol class="items">
                        <?php foreach ($_categories as $_category): ?>
                            <?php if ($_category->getIsActive()): ?>
                                <li class="item">
                                    <a href="<?php echo $block->getCategoryUrl($_category) ?>"<?php if ($block->isCategoryActive($_category)): ?> class="current"<?php endif; ?>><?php echo $block->escapeHtml($_category->getName()) ?></a>
                                    <span class="count"><?php echo $_category->getProductCount() ?></span>
                                </li>
                            <?php endif; ?>
                        <?php endforeach ?>
                    </ol>
                </dd>
            </dl>
        </div>
    </div>
<?php endif;*/ ?>
<div class="home-side-menu-type2" style="margin-bottom:20px;">
    <h2><em class="porto-icon-menu"></em> <?php echo __('Shop Categories');?></h2>
    <div class="side-block side-menu-type2">
        <?php echo $this->getLayout()->createBlock('Smartwave\Porto\Block\CategoryCollection')->setTemplate('Smartwave_Porto::category_side_2.phtml')->toHtml();?>
    </div>
</div>
<?php //echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('call_me_block')->toHtml();?>
